import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";

import "./globals.css";
import { Toaster } from "./components/shadcn/sonner";

// Metadata for SEO
export const metadata: Metadata = {
  title: "HeyHo! | To Do List",
  description: "Generated by create next app",
};

// RootLayout component
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable} scroll-smooth`}>
      <body className="bg-neutral-900 text-neutral-50 antialiased max-h-screen h-screen text-sm font-sans ">
        {/* Main content area */}

        <main>{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
